# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pinkslips.Conversation')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('pword', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=0)),
                ('make', models.CharField(default='', max_length=255)),
                ('model', models.CharField(default='', max_length=255)),
                ('weight', models.IntegerField(default=0)),
                ('desc', models.TextField(default='')),
                ('power', models.IntegerField(default=0)),
                ('dtrain', models.CharField(default='', max_length=255)),
                ('disliked_users', models.ManyToManyField(related_name='haters', to='pinkslips.User')),
                ('liked_users', models.ManyToManyField(related_name='likers', to='pinkslips.User')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_msgs', to='pinkslips.User'),
        ),
        migrations.AddField(
            model_name='image',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='pinkslips.User'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='speaker1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='pinkslips.User'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='speaker2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_2', to='pinkslips.User'),
        ),
    ]
