# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkslips', '0002_auto_20180302_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploader',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
