# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkslips', '0004_auto_20180302_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
