# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkslips', '0005_auto_20180302_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
