# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinkslips', '0006_auto_20180302_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
