# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkslips', '0008_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploader',
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
